[flake8]
max-line-length = 88
ignore = E203, W503, E501, E231  # Black

[metadata]
version = 0.52.0+lineaje.1
maintainer = Lineaje DepFixer
maintainer_email = 221268890+Lineaje-DepFixer@users.noreply.github.com
url = https://github.com/lineaje-labs-gos/pennersr-django-allauth
project_urls = Homepage = https://github.com/lineaje-labs-gos/pennersr-django-allauth
	Repository = https://github.com/lineaje-labs-gos/pennersr-django-allauth
	Tracker = https://github.com/lineaje-labs-gos/pennersr-django-allauth/issues

